name: Build website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install gems
        run: cd website && bundle install

      - name: Install npm dependencies
        run: cd website && npm ci

      - name: Build website
        run: cd website && bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Archive artifact
        run: tar --directory website/_site -cvf "$RUNNER_TEMP/artifact.tar" .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
